

USE customer_behavior;
SHOW TABLES;
select * from customer limit 20

#1.what is the revenue generated by male vs female customer ?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender;

#2.which customer  used a discount  but still they spent more than the average purchase amount ?
select customer_id, purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

#3.which are the top 5 products with highest averge review rating?
select item_purchased, Round(AVG (review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5; 



